# -*- coding: utf-8 -*-
"""Day 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C6_AO99iHTy80JBax0mN8NWdgqv8je-w
"""

class Calculator:
    def __init__(self):
        pass

    def add(self, x, y):
        return x + y

    def subtract(self, x, y):
        return x - y

    def multiply(self, x, y):
        return x * y

    def divide(self, x, y):
        if y == 0:
            return "Error! Division by zero."
        else:
            return x / y
calc = Calculator()
while True:
        print("\nSelect operation:")
        print("1. Addition")
        print("2. Subtraction")
        print("3. Multiplication")
        print("4. Division")
        print("5. Exit")

        choice = input("Enter choice (1/2/3/4/5): ")

        if choice == '5':
            print("Exiting the calculator. Goodbye!")
            break

        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print("Result:", calc.add(num1, num2))
        elif choice == '2':
            print("Result:", calc.subtract(num1, num2))
        elif choice == '3':
            print("Result:", calc.multiply(num1, num2))
        elif choice == '4':
            print("Result:", calc.divide(num1, num2))
        else:
            print("Invalid choice! Please enter a valid option.")



class Calculator:
    def __init__(self):
        pass

    def calculate(self, expression):

        return eval(expression)

calc = Calculator()

while True:
    expression = input("Enter an arithmetic expression (or 'exit' to quit): ")

    if expression == 'exit':
        break

    try:
        result = calc.calculate(expression)
        print("Result:", result)
    except Exception as e:
        print("Invalid expression:", e)